using System.Globalization;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;
using System.Text.Json;
using YoUI.Assets;

namespace YoUI.Editor;

public sealed record ExportContext(UiAsset Asset);
public sealed record ExportFile(string RelativePath, string Content);
/// <summary>Trusted local extension contract. Exporters return artifacts; the host validates and writes paths.</summary>
public interface IUiExporter
{
    string Id { get; }
    string DisplayName { get; }
    IReadOnlyList<ExportFile> Export(ExportContext context);
}

public sealed class ExportCatalog
{
    private readonly List<IUiExporter> exporters = [new JsonExporter(), new CSharpExporter()];
    public IReadOnlyList<IUiExporter> Exporters => exporters.AsReadOnly();
    public IReadOnlyList<IUiExporter> LoadPlugin(string assemblyPath)
    {
        var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(Path.GetFullPath(assemblyPath));
        var found = assembly.GetExportedTypes().Where(t => !t.IsAbstract && !t.IsInterface && typeof(IUiExporter).IsAssignableFrom(t)).Select(t => (IUiExporter)Activator.CreateInstance(t)!).ToArray();
        if (found.Length == 0) throw new InvalidDataException("This assembly contains no IUiExporter implementation.");
        var ids = exporters.Select(e => e.Id).ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach (var e in found) if (string.IsNullOrWhiteSpace(e.Id) || string.IsNullOrWhiteSpace(e.DisplayName) || !ids.Add(e.Id)) throw new InvalidDataException("Exporter IDs must be non-empty and unique.");
        exporters.AddRange(found); return found;
    }
    public static void Write(IUiExporter exporter, UiAsset asset, string directory)
    {
        // Snapshot prevents an exporter from mutating the active editor document.
        var files = exporter.Export(new(UiAssetJson.Parse(UiAssetJson.Serialize(asset))));
        if (files is null || files.Count is < 1 or > 64) throw new InvalidDataException("Exporter must produce 1–64 files.");
        string root = Path.GetFullPath(directory);
        if (Directory.Exists(root) || File.Exists(root)) throw new IOException("Export folder already exists. Choose a new name to preserve previous exports.");
        var unique = new HashSet<string>(StringComparer.OrdinalIgnoreCase); long length = 0;
        foreach (var f in files)
        {
            if (f is null || string.IsNullOrWhiteSpace(f.RelativePath) || f.Content is null || Path.IsPathRooted(f.RelativePath) || f.RelativePath.Contains(':') || f.RelativePath.Split('/', '\\').Any(p => p is "" or "." or ".." || p.EndsWith('.') || p.EndsWith(' ')) || !unique.Add(f.RelativePath.Replace('\\', '/'))) throw new InvalidDataException("Exporter returned an invalid or duplicate relative path.");
            string target = Path.GetFullPath(Path.Combine(root, f.RelativePath));
            if (!target.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase)) throw new InvalidDataException("Export path escapes its destination.");
            length += Encoding.UTF8.GetByteCount(f.Content); if (length > 8 * 1024 * 1024) throw new InvalidDataException("Export exceeds 8 MiB.");
        }
        string staging = root + ".staging-" + Guid.NewGuid().ToString("N");
        try
        {
            Directory.CreateDirectory(staging);
            foreach (var f in files) { var path = Path.Combine(staging, f.RelativePath); Directory.CreateDirectory(Path.GetDirectoryName(path)!); File.WriteAllText(path, f.Content, new UTF8Encoding(false)); }
            Directory.Move(staging, root);
        }
        finally { if (Directory.Exists(staging)) Directory.Delete(staging, true); }
    }
}

public sealed class JsonExporter : IUiExporter
{
    public string Id => "youi.json";
    public string DisplayName => "UI configuration";
    public IReadOnlyList<ExportFile> Export(ExportContext context) => [new("screen.youi.json", UiAssetJson.Serialize(context.Asset))];
}

public sealed class CSharpExporter : IUiExporter
{
    public string Id => "youi.csharp";
    public string DisplayName => "C# + configuration";
    private static string S(string text) => JsonSerializer.Serialize(text);
    private static string F(float value) => value.ToString("R", CultureInfo.InvariantCulture) + "f";
    private static string B(bool value) => value ? "true" : "false";
    private static string C(string value) { var c = UiAssetJson.ParseColor(value); return $"new Color({F(c.R)}, {F(c.G)}, {F(c.B)}, {F(c.A)})"; }
    public IReadOnlyList<ExportFile> Export(ExportContext context)
    {
        var asset = context.Asset; UiAssetJson.Validate(asset);
        var sb = new StringBuilder("// Generated by YoUI Editor. Requires the YoUI runtime library only.\n#nullable enable\nusing System;\nusing System.Collections.Generic;\nusing YoUI;\nusing YoUI.Assets;\n\nnamespace YoUI.Generated;\n\npublic static class Screen\n{\n    public static UiInstance Create(Action<string>? command = null)\n    {\n        var nodes = new Dictionary<string, Element>();\n");
        int index = 0;
        string Emit(UiNode n, UiNode? parent, string? parentVariable)
        {
            string v = "n" + index++; string type = n.Kind switch
            {
                NodeKind.Text => $"Label({S(n.Text)})", NodeKind.Button => $"Button({S(n.Text)})", NodeKind.Toggle => $"Toggle({S(n.Text)}, {B(n.Checked)})", NodeKind.TextBox => "TextBox()", NodeKind.Slider => "Slider()", NodeKind.VerticalStack or NodeKind.HorizontalStack => "StackPanel()", _ => "Element()"
            };
            sb.AppendLine($"        var {v} = new {type} {{ Name = {S(n.Name)}{(n.IsStack ? $", Horizontal = {B(n.Kind == NodeKind.HorizontalStack)}, Gap = {F(n.Gap)}" : "")}{(n.Kind == NodeKind.TextBox ? $", Placeholder = {S(n.Name)}" : "")} }};");
            sb.AppendLine($"        {v}.Background = {C(n.Fill)}; {v}.Radius = {F(n.Radius)}; {v}.Padding = {F(n.Padding)};");
            sb.AppendLine($"        {v}.InheritedOpacity = {F(n.Opacity)}; {v}.Visible = {B(n.Visible)}; {v}.Enabled = {B(n.Enabled)}; {v}.ClipToBounds = {B(n.Clip)}; {v}.Grow = {F(n.Grow)};");
            if (parent?.IsStack == true) sb.AppendLine($"        {v}.Width = {F(n.Width)}; {v}.Height = {F(n.Height)};");
            else if (parent != null)
            {
                var t = n.Transform;
                string transform = $"new RectTransform(new({F(t.AnchorMin.X)}, {F(t.AnchorMin.Y)}), new({F(t.AnchorMax.X)}, {F(t.AnchorMax.Y)}), new({F(t.Pivot.X)}, {F(t.Pivot.Y)}), new({F(t.Position.X)}, {F(t.Position.Y)}), new({F(t.SizeDelta.X)}, {F(t.SizeDelta.Y)}))";
                sb.AppendLine($"        {v}.Transform = {transform};");
            }
            string color = n.Foreground.Length == 0 ? "null" : C(n.Foreground);
            if (n.Kind == NodeKind.Text) sb.AppendLine($"        {v}.Text = {S(n.Text)}; {v}.FontSize = {F(n.FontSize)}; {v}.Bold = {B(n.Bold)}; {v}.Color = {color};");
            if (n.Kind == NodeKind.TextBox) sb.AppendLine($"        {v}.Text = {S(n.Text)};");
            if (n.Kind == NodeKind.Slider) sb.AppendLine($"        {v}.Value = {F(n.Value)};");
            if (n.Kind is NodeKind.Button or NodeKind.Toggle)
            {
                sb.AppendLine($"        {v}.Primary = {B(n.Primary)}; {v}.Caption.FontSize = {F(n.FontSize)}; {v}.Caption.Bold = {B(n.Bold)}; {v}.TextColor = {color};");
                if (n.Command.Length != 0) sb.AppendLine($"        {v}.Clicked += () => command?.Invoke({S(n.Command)});");
            }
            sb.AppendLine($"        nodes.Add({S(n.Id)}, {v});"); if (parentVariable != null) sb.AppendLine($"        {parentVariable}.Add({v});");
            foreach (var child in n.Children) Emit(child, n, v); return v;
        }
        string root = Emit(asset.Root, null, null);
        sb.AppendLine($"        return new UiInstance({root}, nodes);\n    }}\n\n    public static UiDocument CreateDocument(ITextMeasurer measurer, Action<string>? command = null)\n        => Create(command).CreateDocument(measurer, {F(asset.Root.Width)}, {F(asset.Root.Height)}, {B(asset.DarkTheme)});\n}}");
        return [new("Screen.g.cs", sb.ToString()), new("screen.youi.json", UiAssetJson.Serialize(asset)), new("README.md", "Generated C# and JSON are equivalent runtime entry points.\n\nReference managed/YoUI/YoUI.csproj, then call YoUI.Generated.Screen.CreateDocument(measurer, command => { /* bind application actions */ });\n\nOr load configuration with UiAssetRuntime.Build(UiAssetJson.Load(path)). No editor or plugin dependency is required at runtime.\n")];
    }
}
